# Generated by Django 4.2 on 2023-06-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_stud_cardno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='couse_id',
            new_name='couse_code',
        ),
        migrations.RemoveField(
            model_name='stud',
            name='cardno',
        ),
        migrations.AddField(
            model_name='record',
            name='rfid',
            field=models.CharField(default='n', max_length=30),
        ),
        migrations.AddField(
            model_name='stud',
            name='rfid',
            field=models.CharField(default='n', max_length=30),
        ),
        migrations.AddField(
            model_name='stud',
            name='roll',
            field=models.IntegerField(default=0),
        ),
    ]
