# Generated by Django 4.2 on 2023-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_rename_couse_id_record_couse_code_remove_stud_cardno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='couse_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='rfid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stud',
            name='rfid',
            field=models.CharField(max_length=30),
        ),
    ]
