# Generated by Django 4.2 on 2023-06-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_record_couse_code_alter_record_rfid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='couse_code',
            new_name='course_code',
        ),
    ]
